### PR TITLE
added italian and catalan

### PR DESCRIPTION
**Pull request by j0rgeSD**
added italian and catalan options

### CODE REVIEW

**Comment by jelhan** [comment]
@j0rgeSD You missed to push the actual translations.

**Comment by j0rgeSD** [comment]
sorry... yes, i will upload them as soon as I can... just learning howto git ;-)

tx for the patience.

**Comment by jelhan** [comment]
@j0rgeSD Please let me know if you need any help concerning git. Normally a `git status` should show you the new dirs (should be `app/locales/it` and `app/locales/ca`) as untracked folders. You could stage them for next commit by `git add app/locales/it` or just `git add .`. Hope you did not deleted the actual translations by accident.

**Comment by j0rgeSD** [comment]
on my fork should be the it, ca translations  folder and also some corrections to english.

I will go over it tomorrow, but I think I have made a different croodle fork from yours :(

**Pull request closed without merging**
