### PR TITLE
Use bootstrap loading spinner

### PR DESCRIPTION
**Pull request by sappor0**
Use the bootstrap spinner https://getbootstrap.com/docs/4.2/components/spinners/

Looks like this:
Screenshot from 2019-06-11 16-59-32

### CODE REVIEW

**Comment by jelhan** [comment]
Awesome. Wasn't aware that Bootstrap includes one.

**Comment by jelhan** [comment]
You need to update the tests as well. They wait for a `svg` element in `[data-test-button="submit"]` as an assertion for the loading spinner. The loading spinner isn't an `svg` element so it's failing. Tests should pass if you replace `waitFor('[data-test-button="submit"] svg')` with `waitFor('[data-test-button="submit"] .spinner-border')` in `tests/acceptance/create-a-poll-test.js` and `tests/acceptance/participate-in-a-poll-test.js`. `<NextButton>` component integration test (`tests/integration/components/next-button-test.js`) needs to be updated as well. The integration test for `<LoadingSpinner>` component (`tests/integration/components/loading-spinner-test.js`) could be deleted in my opinion as the component is trivial now. If not it has to be updated as well.

Let me know if you don't have the time for fixing the tests. In that case I will merge into my feature branch and do it myself.

**Comment by sappor0** [comment]
ping @jelhan

**Comment by jelhan** [comment]
Thanks a lot. Test failure is not related to this changes. BrowserStack tests against IE11 doesn't seem to be stable. :disappointed:

**Pull request merged**
